import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile, interpolate, useVideoConfig } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";

import { SCENE, SCENE_STARTS, TOTAL_FRAMES, TRANSITION_FRAMES, VO_DELAY } from "./constants";
import { Scene01Hook }         from "./scenes/Scene01Hook";
import { Scene02Solution }     from "./scenes/Scene02Solution";
import { Scene03Dashboard }    from "./scenes/Scene03Dashboard";
import { Scene04Timer }        from "./scenes/Scene04Timer";
import { Scene05Timeline }     from "./scenes/Scene05Timeline";
import { Scene06Reports }      from "./scenes/Scene06Reports";
import { Scene07TeamAdmin }    from "./scenes/Scene07TeamAdmin";
import { Scene08Integrations } from "./scenes/Scene08Integrations";
import { Scene09CTA }          from "./scenes/Scene09CTA";

const transition = fade();
const timing     = linearTiming({ durationInFrames: TRANSITION_FRAMES });

// ─── Voiceover file list — generated by generate-voiceover.ts ────────────────
const VO_FILES = [
  "voiceover/scene-01.mp3",
  "voiceover/scene-02.mp3",
  "voiceover/scene-03.mp3",
  "voiceover/scene-04.mp3",
  "voiceover/scene-05.mp3",
  "voiceover/scene-06.mp3",
  "voiceover/scene-07.mp3",
  "voiceover/scene-08.mp3",
  "voiceover/scene-09.mp3",
] as const;

// ─── Background music ─────────────────────────────────────────────────────────
// Place an ambient/corporate MP3 at: public/music/background.mp3
// Recommended (royalty-free):
//   • Pixabay — "Inspiring Corporate" or "Ambient Technology"
//     https://pixabay.com/music/search/corporate%20ambient/
//   • YouTube Audio Library — "Inspiring" > Ambient > Instrumental
//     https://studio.youtube.com/channel/music
//   • Bensound — "Inspire" or "Perception"
//     https://www.bensound.com/royalty-free-music/track/inspire
//
// Ideal spec: 90–120 BPM, no vocals, subtle pad/piano, gentle dynamics.
const MUSIC_FILE = "music/background.mp3";
const MUSIC_VOLUME = 0.12; // background stays well under the VO at 12%

// ─── Background music component ───────────────────────────────────────────────
const BackgroundMusic: React.FC = () => {
  const { fps, durationInFrames } = useVideoConfig();

  // Fade-in over first 2 seconds, fade-out over last 3 seconds
  const volume = (f: number) =>
    interpolate(
      f,
      [0, 2 * fps, durationInFrames - 3 * fps, durationInFrames],
      [0, MUSIC_VOLUME, MUSIC_VOLUME, 0],
      { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
    );

  return (
    <Audio
      src={staticFile(MUSIC_FILE)}
      loop
      volume={volume}
    />
  );
};

// ─── Voiceover layer ──────────────────────────────────────────────────────────
// Each clip is placed at its scene's absolute start frame + VO_DELAY.
// The VO_DELAY clears the crossfade so the voice enters on a clean frame.
const VoiceoverTracks: React.FC = () => (
  <>
    {VO_FILES.map((file, i) => (
      <Sequence key={file} from={SCENE_STARTS[i] + VO_DELAY} layout="none">
        <Audio src={staticFile(file)} volume={1} />
      </Sequence>
    ))}
  </>
);

// ─── Main composition ─────────────────────────────────────────────────────────
export const DemoVideo: React.FC = () => {
  return (
    <AbsoluteFill>
      {/* ── Audio layer (renders silently, no visual output) ─────────────── */}
      <BackgroundMusic />
      <VoiceoverTracks />

      {/* ── Visual layer ─────────────────────────────────────────────────── */}
      <TransitionSeries>
        <TransitionSeries.Sequence durationInFrames={SCENE.HOOK}>
          <Scene01Hook />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition presentation={transition} timing={timing} />

        <TransitionSeries.Sequence durationInFrames={SCENE.SOLUTION}>
          <Scene02Solution />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition presentation={transition} timing={timing} />

        <TransitionSeries.Sequence durationInFrames={SCENE.DASHBOARD}>
          <Scene03Dashboard />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition presentation={transition} timing={timing} />

        <TransitionSeries.Sequence durationInFrames={SCENE.TIMER}>
          <Scene04Timer />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition presentation={transition} timing={timing} />

        <TransitionSeries.Sequence durationInFrames={SCENE.TIMELINE}>
          <Scene05Timeline />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition presentation={transition} timing={timing} />

        <TransitionSeries.Sequence durationInFrames={SCENE.REPORTS}>
          <Scene06Reports />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition presentation={transition} timing={timing} />

        <TransitionSeries.Sequence durationInFrames={SCENE.TEAM_ADMIN}>
          <Scene07TeamAdmin />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition presentation={transition} timing={timing} />

        <TransitionSeries.Sequence durationInFrames={SCENE.INTEGRATIONS}>
          <Scene08Integrations />
        </TransitionSeries.Sequence>

        <TransitionSeries.Transition presentation={transition} timing={timing} />

        <TransitionSeries.Sequence durationInFrames={SCENE.CTA}>
          <Scene09CTA />
        </TransitionSeries.Sequence>
      </TransitionSeries>
    </AbsoluteFill>
  );
};
